hl.env("CARGO_HOME", os.getenv("XDG_DATA_HOME") .. "/cargo")
hl.env("CLUTTER_BACKEND", "wayland")
hl.env("EDITOR", "nvim")
hl.env("ELECTRON_OZONE_PLATFORM_HINT", "auto")
hl.env("GDK_BACKEND", "wayland,x11")
hl.env("GNUPGHOME", os.getenv("XDG_DATA_HOME") .. "/gnupg")
hl.env("GOPATH", os.getenv("XDG_DATA_HOME") .. "/go")
hl.env("HYPRCURSOR_SIZE", "24")
hl.env("HYPRCURSOR_THEME", "Bibata-Modern-Classic")
hl.env("HYPRSHOT_DIR", os.getenv("HOME") .. "/Imágenes/Capturas")
hl.env("LESSHISTFILE", os.getenv("XDG_CACHE_HOME") .. "/less/history")
hl.env("PAGER", "less")
hl.env("QT_AUTO_SCREEN_SCALE_FACTOR", "1")
hl.env("QT_QPA_PLATFORM", "wayland;xcb")
hl.env("QT_QPA_PLATFORMTHEME", "hyprqt6engine")
hl.env("QT_WAYLAND_DISABLE_WINDOWDECORATION", "1")
hl.env("XDG_CACHE_HOME", os.getenv("HOME") .. "/.cache")
hl.env("XDG_CONFIG_HOME", os.getenv("HOME") .. "/.config")
hl.env("XDG_CURRENT_DESKTOP", "Hyprland")
hl.env("XDG_DATA_HOME", os.getenv("HOME") .. "/.local/share")
hl.env("XDG_SESSION_DESKTOP", "Hyprland")
hl.env("XDG_SESSION_TYPE", "wayland")
hl.env("XDG_STATE_HOME", os.getenv("HOME") .. "/.local/state")
