hl.on("hyprland.start", function()
	hl.exec_cmd("bash ~/.config/hypr/scripts/wallpaper.sh")
	hl.exec_cmd("dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP")
	hl.exec_cmd("bash ./scripts/wine.sh")
	hl.exec_cmd("bash ./scripts/sounds.sh")
	hl.exec_cmd("/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1")
	hl.exec_cmd("udiskie --no-automount --tray")
	hl.exec_cmd("cbatticon")
	hl.exec_cmd("quickshell -c minecraft")
	hl.exec_cmd("wl-clip-persist --clipboard regular")
	hl.exec_cmd("wl-paste --type text --watch cliphist store")
	hl.exec_cmd("wl-paste --type image --watch cliphist store")
	hl.exec_cmd("nm-applet --indicator")
	hl.exec_cmd("swayosd-server")
	hl.exec_cmd("ydotoold")
	hl.exec_cmd("mega-cmd-server")
	hl.exec_cmd("dolphin --daemon")
	hl.exec_cmd("hypridle")
	hl.exec_cmd("hyprlock")
  require("noip")
end)
